project_id = "ajzwmubhzpnzjbdffoqi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
image_transformation.enabled = true

[auth]
enabled = true
port = 54328

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[edge_runtime]
enabled = true
port = 54329

[[edge_runtime.policy]]
id = "policy_0"
allowed_paths = ["https://*", "http://*"]

[functions.analyze-job-fit]
verify_jwt = true

[functions.parse-resume]
verify_jwt = true

[functions.generate-resume-bullets]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true
