project_id = "ajzwmubhzpnzjbdffoqi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
# Removed: port = 54327 (no longer valid)
file_size_limit = "50MiB"

[storage.image_transformation]
enabled = true

[auth]
enabled = true
# Removed: port = 54328 (no longer valid)
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[edge_runtime]
enabled = true
# Removed: port = 54329 (no longer valid)
policy = "per_worker"
inspector_port = 8083

[functions.analyze-job-fit]
verify_jwt = true

[functions.parse-resume]
verify_jwt = true

[functions.generate-resume-bullets]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true