export const AI_CONFIG = {
  MODEL: 'gpt-4o-mini',
  TEMPERATURE_MATCHING: 0.0,  // Changed from 0.1
  TEMPERATURE_BULLETS: 0.15,   // New
  MAX_RETRIES: 2,
  STAGE1_MAX_TOKENS: 3000,
  STAGE2A_MAX_TOKENS: 4000,    // Changed from STAGE2_MAX_TOKENS: 8000
  STAGE2B_MAX_TOKENS: 4000,    // New
};
