// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajzwmubhzpnzjbdffoqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqendtdWJoenBuempiZGZmb3FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzcxNjksImV4cCI6MjA3MzQ1MzE2OX0.h-melc4B7d8bfLEYL4NWXhouVF3xGAhGJfaxmp8SlOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});